In [ ]:
pip install numpy


In [ ]:
import numpy as np
arr_1d=np.array([1,2,3])
print(arr_1d)

[1 2 3]


In [ ]:
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)
print(arr_2d.ndim)


[[1 2 3]
 [4 5 6]]
2


In [ ]:
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)
print(arr_3d.ndim)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
3


In [ ]:
zeroes=np.zeros((2,3))
print(zeroes)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
ones=np.ones((3,3))
print(ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
r_arr=np.random.random((3,3))
print(r_arr)

[[0.90102449 0.03052434 0.79197274]
 [0.6499561  0.12184556 0.42827012]
 [0.87057792 0.9097024  0.24510982]]


In [ ]:
identity=np.eye(3)
print(identity)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
range_arr=np.arange(0,10,3)#start,stop,step
print(range_arr)

[0 3 6 9]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print("Shape:",arr.shape)
print("Size:",arr.size)
print("Dimension:",arr.ndim)
print("Data type:",arr.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Data type: int64


You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity

In [ ]:
gh1=np.array([22,25,20])
gh2=np.array([24,26,23])
temp_data=np.array([gh1,gh2])
print(temp_data)

[[22 25 20]
 [24 26 23]]


In [ ]:
print("Shape:",temp_data.shape)
print("Size:",temp_data.size)
print("Dimension:",temp_data.ndim)
print("Data type:",temp_data.dtype)

Shape: (2, 3)
Size: 6
Dimension: 2
Data type: int64


In [ ]:
gh3=np.array([21, 23, 22])
updated_temp_data=np.array([gh1,gh2,gh3])
print(updated_temp_data)

[[22 25 20]
 [24 26 23]
 [21 23 22]]


In [ ]:
sensor_error_flags=np.zeros((2,3))
print(sensor_error_flags)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print("Updated array:\n",updated_temp_data)
print("Sensor error flags:\n",sensor_error_flags)
print("Greenhouse identity:\n",greenhouse_identity)

Updated array:
 [[22 25 20]
 [24 26 23]
 [21 23 22]]
Sensor error flags:
 [[0. 0. 0.]
 [0. 0. 0.]]
Greenhouse identity:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0,1])
print(arr[1,0])
print(arr[:,1:])

2
4
[[2 3]
 [5 6]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.

The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array

Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.


In [ ]:
apples=np.array([50,60,55,70,65,80,90])
oranges=np.array([40,45,50,60,55,70,75])
shipments=np.array([apples,oranges])
print("Apples shipped on wednesday are:",shipments[0,2])

55


In [ ]:
print("Oranges shipped on sunday are:",shipments[1,6])

Oranges shipped on sunday are: 75


In [ ]:
print("Mon-Fri\n",shipments[:,0:5])

Mon-Fri
 [[50 60 55 70 65]
 [40 45 50 60 55]]


In [ ]:
print("Weekend\n",shipments[:,5:7])

Weekend
 [[80 90]
 [70 75]]


In [ ]:
print("Apples from wednesday to saturday\n",shipments[0:1,2:6])

Apples from wednesday to saturday
 [[55 70 65 80]]


In [ ]:
print("Shipments before replacement:",shipments[0,5])
shipments[0,5]=100
print("Shipments after replacement:",shipments[0,5])

Shipments before replacement: 80
Shipments after replacement: 100


In [ ]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print("Addition:",(a+b))
print("Subtraction:",(a-b))
print("Multiplication:",(a*b))
print("Multiplication by 2:",(a*2))
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
b1=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix Multiplication:\n",np.dot(a1,b1))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Multiplication by 2: [2 4 6]
Matrix Multiplication:
 [[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


In [ ]:
#Broadcast
a=np.array([1,2,3])
b=2
print(a+b)

[3 4 5]


In [ ]:
x=np.array([1,2])
y=np.array([1,1])
print("\n1. Arithmetic ufuncs\n")
print(np.add(x, y))
print(np.subtract(x, y))
print(np.multiply(x, y))
print(np.divide(x, y))
print(np.power(x, y))
print(np.mod(x, y))
print("\n2. Exponential and Logarithmic ufuncs\n")
print(np.exp(x))
print(np.log(x))
print(np.log10(x))
print(np.log2(x))
print(np.expm1(x))
print("\n3. Trigonometric ufuncs\n")
print(np.sin(x))
print(np.cos(x))
print(np.tan(x))
print(np.arcsin(x))
print(np.arccos(x))
print(np.arctan(x))
print(np.degrees(x))
print(np.radians(x))
print("\n4. Rounding ufuncs\n")
print(np.round(x))
print(np.floor(x))
print(np.ceil(x))
print(np.trunc(x))
print("\n5. Statistical ufuncs\n")
print(np.min(x))
print(np.max(x))
print(np.mean(x))
print(np.std(x))
print(np.var(x))
print(np.sum(x))
print(np.prod(x))
print("\n6. Logical ufuncs\n")
print(np.logical_and(x, y))
print(np.logical_or(x, y))
print(np.logical_not(x))
print(np.logical_xor(x, y))
print("\n7. Comparison ufuncs\n")
print(np.greater(x, y))
print(np.less(x, y))
print(np.equal(x, y))
print(np.not_equal(x, y))
print(np.greater_equal(x, y))
print(np.less_equal(x, y))
print("\n8. Bitwise ufuncs\n")
print(np.bitwise_and(x, y))
print(np.bitwise_or(x, y))
print(np.bitwise_xor(x, y))
print(np.invert(x))


1. Arithmetic ufuncs

[2 3]
[0 1]
[1 2]
[1. 2.]
[1 2]
[0 0]

2. Exponential and Logarithmic ufuncs

[2.71828183 7.3890561 ]
[0.         0.69314718]
[0.      0.30103]
[0. 1.]
[1.71828183 6.3890561 ]

3. Trigonometric ufuncs

[0.84147098 0.90929743]
[ 0.54030231 -0.41614684]
[ 1.55740772 -2.18503986]
[1.57079633        nan]
[ 0. nan]
[0.78539816 1.10714872]
[ 57.29577951 114.59155903]
[0.01745329 0.03490659]

4. Rounding ufuncs

[1 2]
[1. 2.]
[1. 2.]
[1. 2.]

5. Statistical ufuncs

1
2
1.5
0.5
0.25
3
2

6. Logical ufuncs

[ True  True]
[ True  True]
[False False]
[False False]

7. Comparison ufuncs

[False  True]
[False False]
[ True False]
[False  True]
[ True  True]
[ True False]

8. Bitwise ufuncs

[1 0]
[1 3]
[0 3]
[-2 -3]


/tmp/ipython-input-1109027406.py:20: RuntimeWarning: invalid value encountered in arcsin
  print(np.arcsin(x))
/tmp/ipython-input-1109027406.py:21: RuntimeWarning: invalid value encountered in arccos
  print(np.arccos(x))


In [ ]:
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC],dtype=float)
print("Shape of production_all:",production_all.shape)

Shape of production_all: (3, 4, 3)


In [ ]:
print("Total production of farmA:")
print("Sum of farmA:\n:",np.sum(farmA))

Total production of farmA:
Sum of farmA:
: 126


In [ ]:
print("Total production of farmB:")
print("Sum of farmB:\n:",np.sum(farmB))

Total production of farmB:
Sum of farmB:
: 234


In [ ]:
print("Total production of farmC:")
print("Sum of farmC:\n:",np.sum(farmC))

Total production of farmC:
Sum of farmC:
: 174


In [ ]:
print("Shape:",production_all.shape)
print("Size:",production_all.size)
print("Dimension:",production_all.ndim)
print("Data type:",production_all.dtype)

Shape: (3, 4, 3)
Size: 36
Dimension: 3
Data type: int64


In [ ]:
print("FarmA Statistical Analysis:")
print("Mean of farmA:\n",np.mean(farmA))
print("Standard deviation of farmA:\n",np.std(farmA))
print("Variance of farmA:\n",np.var(farmA))



FarmA Statistical Analysis:
Mean of farmA:
 10.5
Standard deviation of farmA:
 1.9790570145063195
Variance of farmA:
 3.9166666666666665


In [ ]:
print("FarmB Statistical Analysis:")
print("Mean of farmB:\n",np.mean(farmB))
print("Standard deviation of farmB:\n",np.std(farmB))
print("Variance of farmB:\n",np.var(farmB))

FarmB Statistical Analysis:
Mean of farmB:
 19.5
Standard deviation of farmB:
 1.9790570145063195
Variance of farmB:
 3.9166666666666665


In [ ]:
print("FarmC Statistical Analysis:")
print("Mean of farmC:\n",np.mean(farmC))
print("Standard deviation of farmC:\n",np.std(farmC))
print("Variance of farmC:\n",np.var(farmC))

FarmC Statistical Analysis:
Mean of farmC:
 14.5
Standard deviation of farmC:
 1.9790570145063195
Variance of farmC:
 3.9166666666666665


In [ ]:
hour_weights=np.array([0.5,1,0.75])
weighted_per_panel_A=np.dot(farmA,hour_weights)
weighted_per_panel_B=np.dot(farmB,hour_weights)
weighted_per_panel_C=np.dot(farmC,hour_weights)
weighted_per_panel=np.array([weighted_per_panel_A,weighted_per_panel_B,weighted_per_panel_C])
print("Weighted PerPanel are:\n",weighted_per_panel)




Weighted PerPanel are:
 [[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]


In [ ]:
production_all[1]=production_all[1]+0.5
print("After ading the offset:\n",production_all)



After ading the offset:
 [[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]


In [ ]:
a=np.array([1,2,3,4,5,6,7,8])
b=a.reshape(4,2)
print("Reshaped array:\n",b)

Reshaped array:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
#splitting
arr=np.array([1,2,3,4,5,6])
print(np.array_split(arr,3))

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
#Advanced indexing
arr=np.array([1,2,3,4,5,6,7,8])
print(arr[arr>3])

[4 5 6 7 8]


In [ ]:
arr=np.array([1,2,3])
x=arr.copy()
arr[0]=10
print(arr)
print(x)
arr=np.array([1,2,3])
x=arr.view()
arr[0]=10
print(arr)
print(x)

[10  2  3]
[1 2 3]
[10  2  3]
[10  2  3]


In [ ]:
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]


In [156]:
a1=np.arange(10,51)
print(a1)
a2=np.random.rand(3,3)
print(a2)

#array attiributes
print("array attirubets")
print(a1.ndim)
print(a1.shape)
print(a1.size)
print(a1.dtype)

#basic
print("---basic operation---")
print(a1+5)
print(a2*2)

#indexing and slicing
print("--indexing and slicing--")
a3=np.arange(1,26)
a3=a3.reshape(5,5)
print(a3)
print(a3.ndim)
print("first row",a3[0,:])
print("last row",a3[4,:])
print("first 3 rows 2 col",a3[0:3,0:2])

#aggergation
print("--aggergation--")
a4 = np.random.randint(10, 101, size=10)
print(a4)
print("max:",a4.max())
print("min:",a4.min())
print("mean:",a4.mean())
print("sum:",a4.sum())

#reshaping
print("--reshaping--")
a5=np.arange(1,13).reshape(3,4)
print(a5)

#boardcasting
print("--boardingcasting--")
a6=np.ones((3,3),dtype=int)
print(a6)
d1=[1,2,3]
print("after adding")
print(a6+d1)

#filtering
print("--filtering--")
a7=np.random.randint(1,51,size=20)
print(a7)
print(a7[a7%5==0])

#matrix multipilaction
print("--matrix multipilaction--")
a8=np.array([[1,2],[3,4]])
a9=np.array([[5,6],[7,8]])
print(np.dot(a8,a9))

#advanced indexing
print("--fancy indexing--")
a10=np.arange(1,17).reshape(4,4)
print(a10)
r=[0,1,2,3]
c=[0,1,2,3]
print(a10[:,])
print("diagonal elements:",a10[[r],[c]])

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.42898714 0.09825642 0.82207564]
 [0.46018199 0.42152048 0.78260369]
 [0.62337225 0.51620057 0.49949892]]
array attirubets
1
(41,)
41
int64
---basic operation---
[15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
[[0.85797428 0.19651284 1.64415129]
 [0.92036398 0.84304097 1.56520737]
 [1.2467445  1.03240113 0.99899783]]
--indexing and slicing--
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
2
first row [1 2 3 4 5]
last row [21 22 23 24 25]
first 3 rows 2 col [[ 1  2]
 [ 6  7]
 [11 12]]
--aggergation--
[76 37 92 99 67 23 95 65 22 42]
max: 99
min: 22
mean: 61.8
sum: 618
--reshaping--
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
--boardingcasting--
[[1 1 1]
 [1 1 1]
 [1 1 1]]
after adding
[[2 3 4]
 [2 3 4]
 [2 3 4]]
--filtering--
[ 6 35 12 26 3